/* Main.c file generated by New Project wizard
 * Author:    Aniket Kumar
 * Created:   Thu May 7 2020
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include<reg51.h>

#define DATA_BUS P0
#define TEMP P1

sbit WRadc = P3 ^ 3; // Write pin. It is used to start the conversion.
sbit RDadc = P3 ^ 4; // Read pin. It is used to extract the data from internal register to the output pins of ADC.
sbit RS = P2 ^ 0; //register select pin
sbit RW = P2 ^ 1; // read Write pin
sbit EN = P2 ^ 2; //enable pin
sbit BZ = P2 ^ 3; //Buzzer

// Define new types
typedef unsigned char uchar;
typedef unsigned int uint;

void LCD_init(void);
void lcdcmd(uchar value);
void lcddata(uchar value);
void printascii(uchar value);
void string(uchar ad, uchar * s);
void display(void);

void delay(uint msec) // The delay function provides delay in msec.
{
    int i, j;
    for (i = 0; i < msec; i++)
        for (j = 0; j < 1275; j++);
}

void main() {
    LCD_init();
    while (1) {
        RDadc = 1;
        WRadc = 0;
        delay(1);
        WRadc = 1;
        delay(1);
        RDadc = 0;
        delay(1);
        string(0x82, "TEMPERATURE:");
        display();
    }
}

void lcdcmd(uchar value) {
    DATA_BUS = value;
    RS = 0;
    RW = 0;
    EN = 1;
    delay(1);
    EN = 0;
    return;
}

void printascii(uchar value) {
    value = value + 0x30; //convert variable x2 to ascii by adding 0x30
    lcddata(value);
    return;
}

void lcddata(uchar value) {
    DATA_BUS = value;
    RS = 1;
    RW = 0;
    EN = 1;
    delay(1);
    EN = 0;
    return;
}

// Initialize LCD controller
void LCD_init(void) {
    lcdcmd(0x38); // 8-bits, 2 lines, 7x5 dots
    lcdcmd(0x0C); // no cursor, no blink, enable display
    lcdcmd(0x06); // auto-increment on
    lcdcmd(0x01); // clear screen
    delay(1);
}

// Display a string
void string(uchar ad, uchar * s) {
    lcdcmd(ad);
    while ( * s > 0) {
        lcddata( * s++);
        delay(1);
    }
}

void convert_display(void) {

    uchar h, t, u;
    lcdcmd(0xC6); //command to set the cursor to 2nd line on 16*2 lcd
    if (TEMP >= 29)
        BZ = 1;
    else
        BZ = 0;
    h = TEMP / 100; //divide the value by 10 and store quotient, hundreds in variable h
    t = (TEMP / 10) - (h * 10); //divide the value by 10 and extract tens in variable t
    u = TEMP % 10; //divide the value by 10 and store remainder, units in variable u
    printascii(h); //display temperature on 16*2 lcd display
    printascii(t);
    printascii(u);
    lcddata(0xDF); //ascii value of degree(°) symbol
    lcddata('C');

}